<%
Const SiteName="专升本招名系统"        '网站名称
Const SiteTitle="专升本招名系统"        '网站标题
Const SiteName2="江西科技师范学院"        '单位名称
Const Siteadd="江西省南昌市红角洲新区学府大道589号"        '单位地址
Const Siteno="330038"        '单位地址
Const Sitetel="0791-3847551"        '单位电话
Const Sitefax="0791-3847551"        '单位传真
Const Sitetel2="13970889105"        '单位传真
Const SiteUrl="http://zsbbm.jxstnu.edu.cn"        '网站地址
Const EnterpriseMail="xieyunc@163.com"        '单位邮局
Const LogoUrl="images/logo3.gif"        'Logo地址
Const BannerUrl="images/top5.jpg"        'Banner地址
Const High=200        '高度
Const WebmasterName="谢祥选"        '管理员姓名
Const WebmasterEmail="xieyunc@gmail.com"        '管理员信箱
Const Copyright="&copy; 版权所有 2011-2011<a href='http://ZsbBm.jxstnu.edu.cn' target='_blank'> 江西科技师范学院专升本报名网</a>"        '版权信息
Const g1="images/g1.gif"        '广告位1 (g1)
Const g2="images/g2.gif"        '广告位1 (g1)
Const g3="images/TC.gif"        '广告位1 (g1)
Const g4="images/logo.gif"        '广告位1 (g1)
Const g5="images/logo.gif"        '广告位1 (g1)
Const g6="images/logo.gif"        '广告位1 (g1)
Const gl1="http://cn/cncn"        '广告链接1 (gl1)
Const gl2="http://cn"        '广告链接1 (gl1)
Const gl3="http://8600"        '广告链接1 (gl1)
Const gl4=""        '广告链接1 (gl1)
Const gl5=""        '广告链接1 (gl1)
Const gl6=""        '广告链接1 (gl1)
Const MaxPerPage_Default=10        '首页每页产品或文章数
Const MaxPerPage_Search=10        '文章搜索页每页文章数
Const ShowContentByPage="Yes"        '文章内容是否分页显示
Const MaxPerPage_Content=200000        '每页显示大约字符数
Const EnableArticleCheck="Yes"        '是否启用文章审核功能
Const EnableUploadFile="Yes"        '是否开放文件上传
Const PopAnnounce="Yes"        '是否弹出公告窗口
Const HitsOfHot=500        '热门文章点击数
Const MaxFileSize=200        '上传文件大小限制
Const SaveUpFilesPath="UploadFiles"        '存放上传文件的目录
'Const UpFileType="gif|jpg|bmp|png|swf|doc|rar|exe"        '允许的上传文件类型
Const UpFileType="gif|jpg|bmp|png"        '允许的上传文件类型
Const DelUpFiles="Yes"        '删除文章时是否同时删除文章中的上传文件
Const SessionTimeout=10        'Session会话的保持时间
Const MailObject="Jmail"        '邮件发送组件
Const MailServer="pop.163.com"        '用来发送邮件的SMTP服务器
Const MailServerUserName="xieyunc@163.com"        '登录用户名
Const MailServerPassWord="999"        '登录密码
Const MailDomain="163.com"        '域名
%>